FROM scratch

ARG SOURCE_REPOSITORY
ARG SOURCE_REVISION
ARG SOURCE_CREATED

LABEL org.opencontainers.image.title="Private multi-language SDK bundle" \
      org.opencontainers.image.description="Tracked source bundle for language SDK consumers" \
      org.opencontainers.image.source="https://github.com/${SOURCE_REPOSITORY}" \
      org.opencontainers.image.revision="${SOURCE_REVISION}" \
      org.opencontainers.image.created="${SOURCE_CREATED}"

COPY . /opt/ores-sdk/
